Resolve (some) browser warnings
fathominfo/delphy-web pull request #7
Opened 2024-09-27 21:06 UTC by kayserifserif

2024-09-30 16:22 UTC, mark-fathom requested changes
Definitely want to keep the MD fonts in there. Although we can't make them available to the general public, they are the primary fonts we use in the version of the app that we publish.

2024-10-01 14:06 UTC, kayserifserif commented
Ahhh. Thanks for the check! Reverted that commit.

2024-10-03 13:39 UTC, kayserifserif commented on src/ts/ui/mutations/mutationprevalencecanvas.ts
> +          (new FontFace("Roboto", "url('/assets/fonts/roboto/roboto-medium.ttf')", {weight: '500', style: 'normal'})).load(),
For some reason, we only have the ttf for medium and bold weights. Other weights have the woff2. Was there any reason for that?

2024-10-04 15:11 UTC, mark-fathom commented on src/ts/ui/mutations/mutationprevalencecanvas.ts
> +          (new FontFace("Roboto", "url('/assets/fonts/roboto/roboto-medium.ttf')", {weight: '500', style: 'normal'})).load(),
If there was, I doubt it was a good one.

2024-10-04 15:27 UTC, mark-fathom commented on src/ts/ui/mutations/mutationprevalencecanvas.ts
> +          (new FontFace("Roboto", "url('/assets/fonts/roboto/roboto-medium.ttf')", {weight: '500', style: 'normal'})).load(),
I stand corrected: it looks like jspdf only works well with ttf fonts. In fact, we had to make a custom conversion of .otf to .ttf fonts to get it to work.

2024-10-04 15:35 UTC, merged